/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小郑的Unity小屋",
  "description": "Unity技术手册",
  "base": "/WebBook/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/work.png",
        "heroText": "小郑的Unity小屋",
        "tagline": "Unity技术手册",
        "actionText": "打开笔记 →",
        "actionLink": "/unitymobile/content",
        "features": [
          {
            "title": "移动端",
            "details": "Unity 移动端相关技术"
          },
          {
            "title": "Editor",
            "details": "Unity 编辑器的二次开发相关技术"
          },
          {
            "title": "VR/AR",
            "details": "VR AR相关的技术文章"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-56aa2e3a",
      "path": "/"
    },
    {
      "title": "模型相关处理",
      "frontmatter": {},
      "regularPath": "/unityeditor/content.html",
      "relativePath": "unityeditor/content.md",
      "key": "v-140a2a18",
      "path": "/unityeditor/content.html"
    },
    {
      "title": "移动端的图片中心对称",
      "frontmatter": {},
      "regularPath": "/unitymobile/content.html",
      "relativePath": "unitymobile/content.md",
      "key": "v-b4d6dc90",
      "path": "/unitymobile/content.html"
    },
    {
      "title": "Oculus",
      "frontmatter": {},
      "regularPath": "/unityvrar/oculus.html",
      "relativePath": "unityvrar/oculus.md",
      "key": "v-ee190850",
      "path": "/unityvrar/oculus.html"
    },
    {
      "title": "Pico 4",
      "frontmatter": {},
      "regularPath": "/unityvrar/pico.html",
      "relativePath": "unityvrar/pico.md",
      "key": "v-6d6a7820",
      "path": "/unityvrar/pico.html"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "nav": [
      {
        "text": "GitHub",
        "link": "https://github.com/MRLesile"
      }
    ],
    "sidebar": [
      {
        "title": "移动端",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/unitymobile/content"
        ]
      },
      {
        "title": "Editor",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/unityeditor/content"
        ]
      },
      {
        "title": "VR/AR",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/unityvrar/oculus",
          "/unityvrar/pico"
        ]
      }
    ]
  }
}