/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小郑的Unity小屋",
  "description": "Unity技术手册",
  "base": "/WebBook/",
  "headTags": [],
  "pages": [
    {
      "title": "目录标题",
      "frontmatter": {},
      "regularPath": "/%20unity/test.html",
      "relativePath": " unity/test.md",
      "key": "v-504cdbf5",
      "path": "/%20unity/test.html",
      "headers": [
        {
          "level": 2,
          "title": "windows安装nvm",
          "slug": "windows安装nvm"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/work.png",
        "heroText": "小郑的Unity小屋",
        "tagline": "Unity技术手册",
        "actionText": "打开笔记 →",
        "actionLink": "/unity/test",
        "features": [
          {
            "title": "移动端",
            "details": "Unity 移动端相关技术"
          },
          {
            "title": "Editor",
            "details": "Unity 编辑器的二次开发相关技术"
          },
          {
            "title": "VR/AR",
            "details": "VR AR相关的技术文章"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-56aa2e3a",
      "path": "/"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "sidebar": [
      {
        "title": "Unity",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/unity/test"
        ]
      }
    ]
  }
}